services:
  - type: web
    name: saudia-career-bot
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
    autoDeploy: true
